apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1000"
  name: k3d-global-argo-cd
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/argo-cd
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  name: k3d-global-caddy
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/caddy
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: k3d-global-cert-manager
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/cert-manager
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: k3d-global-defn
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/defn
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: k3d-global-defn-shared
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/defn-shared
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: k3d-global-external-dns
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/external-dns
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-global-external-secrets-operator
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/external-secrets-operator
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: k3d-global-knative
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/knative
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: k3d-global-kourier
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/kourier
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k3d-global-kyverno
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/kyverno
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-global-pod-identity-webhook
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/pod-identity-webhook
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: k3d-global-secrets-store
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/k3d-global-secrets-store
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: k3d-global-tfo
  namespace: argocd
spec:
  destination:
    name: k3d-global
  project: default
  source:
    path: k/tfo
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
