#ManagedBy: cue

patches: []
resources:
  - resource-namespace-external-dns.yaml
namespace: external-dns
helmCharts:
  - releaseName: external-dns
    name: external-dns
    version: 6.7.2
    repo: https://charts.bitnami.com/bitnami
    namespace: external-dns
    valuesInline:
      sources:
        - service
        - ingress
      provider: cloudflare
    includeCRDs: true
