#ManagedBy: cue

patches: []
resources: []
namespace: default
helmCharts:
  - releaseName: pod-identity-webhook
    name: amazon-eks-pod-identity-webhook
    version: 1.2.0
    repo: https://jkroepke.github.io/helm-charts
    namespace: default
    valuesInline:
      pki:
        certManager:
          certificate:
            duration: 2160h0m0s
            renewBefore: 360h0m0s
    includeCRDs: true
