#ManagedBy: cue

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.defn.run
spec:
  loadBalancerClass: tailscale
