#ManagedBy: cue

patches: []
namespace: nginx
resources: []
helmCharts:
  - releaseName: nginx
    namespace: nginx
    valuesInline: {}
    name: nginx
    version: 13.2.34
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: true
