repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^app/(provider|cdktf.out|.local)/|\.lock|local|tf/terraform-
      - id: end-of-file-fixer
        exclude: ^app/(provider|cdktf.out|.local|tf|k)/|^gen|\.lock|local|main.tf.json|VERSION|VENDOR|REVISION|tf/terraform-
      - id: check-json
        exclude: ^app/(provider|cdktf.out|.local)/|tf/terraform-
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
        exclude: ^app/(provider|cdktf.out|.local)/|local|/charts/|tf/terraform-
      - id: check-toml
        exclude: ^app/(provider|cdktf.out|.local)/|local|tf/terraform-
      - id: check-shebang-scripts-are-executable
        exclude: ^app/(provider|cdktf.out|.local)/|local|tf/terraform-
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: ^app/(provider|cdktf.out|.local|tf|k)/|local|main.tf.json|tf/terraform-
