#ManagedBy: cue

apiVersion: v1
kind: Service
metadata:
  name: caddy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.defn.run
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
