#ManagedBy: cue

patches:
  - path: patch-service-tailscale.yaml
resources:
  - resource-namespace-caddy.yaml
namespace: caddy
helmCharts:
  - releaseName: caddy
    name: caddy
    version: 0.2.4
    repo: https://charts.alekc.dev
    namespace: caddy
    valuesInline:
      listenPort: 80
      https:
        enabled: true
        port: 443
      config:
        caddyFile: |-
          map {http.request.host.labels.2} $upstream_scheme {
          	default http
          }

          https://argocd.defn.run {
          	tls /certs/tls.crt /certs/tls.key
          	reverse_proxy https://argocd-server.argocd.svc.cluster.local {
          		transport http {
          			tls
          			tls_insecure_skip_verify
          		}
          	}
          }

          https://*.defn.run {
          	tls /certs/tls.crt /certs/tls.key
          	reverse_proxy {$upstream_scheme}://{http.request.host.labels.2}.default.svc.cluster.local {
          		header_up -Host
          		header_up X-defn-label0	"{http.request.host.labels.0}"
          		header_up X-defn-label1	"{http.request.host.labels.1}"
          		header_up X-defn-label2	"{http.request.host.labels.2}"
          	}
          }
        global: |-
          local_certs
          log {
          	output stdout
          }
      volumes:
        - name: certs
          secret:
            secretName: defn-run-wildcard
            optional: false
      volumeMounts:
        - name: certs
          mountPath: /certs
    includeCRDs: true
