apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  name: bye
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  name: hello
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
