apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: defn-run-wildcard
  namespace: caddy
spec:
  dnsNames:
  - '*.defn.run'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: zerossl-production
  secretName: defn-run-wildcard
