helmCharts:
- includeCRDs: true
  name: external-dns
  namespace: external-dns
  releaseName: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns
  valuesInline:
    domainFilters:
    - defn.run
    provider: cloudflare
    sources:
    - service
    - ingress
  version: 1.12.2
namespace: external-dns
resources:
- resource-namespace-external-dns.yaml
