apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k3d-control-cert-manager
  namespace: argocd
spec:
  destination:
    name: k3d-control
  project: default
  source:
    path: r/cert-manager
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-control-external-secrets-operator
  namespace: argocd
spec:
  destination:
    name: k3d-control
  project: default
  source:
    path: r/external-secrets-operator
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-control-pod-identity-webhook
  namespace: argocd
spec:
  destination:
    name: k3d-control
  project: default
  source:
    path: r/pod-identity-webhook
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: k3d-control-secrets-store
  namespace: argocd
spec:
  destination:
    name: k3d-control
  project: default
  source:
    path: r/k3d-control-secrets-store
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
