#ManagedBy: cue

patches: []
resources:
  - resource-namespace-keda.yaml
namespace: keda
helmCharts:
  - releaseName: keda
    name: keda
    version: 2.8.2
    repo: https://kedacore.github.io/charts
    namespace: keda
    valuesInline: {}
    includeCRDs: true
