#ManagedBy: cue

patches: []
resources: []
helmCharts:
  - releaseName: bootstrap
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    valuesInline:
      anyResources:
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/m
              targetRevision: main
              path: k/cert-manager/release
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        pod-identity-webhook: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-pod-identity-webhook
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/m
              targetRevision: main
              path: k/pod-identity-webhook/release
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        external-secrets-operator: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-external-secrets-operator
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/m
              targetRevision: main
              path: k/external-secrets-operator/release
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        k3d-control-secrets-store: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-secrets-store
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/m
              targetRevision: main
              path: k/k3d-control-secrets-store/release
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
    includeCRDs: true
