#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev
spec:
  provider:
    vault:
      server: http://vault.defn.run:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: k3d-control
          role: external-secrets
