helmCharts:
- includeCRDs: true
  name: coder
  namespace: coder
  releaseName: coder
  repo: https://helm.coder.com/v2
  valuesInline:
    coder:
      service:
        type: ClusterIP
    env:
    - name: CODER_ACCESS_URL
      valueFrom:
        secretKeyRef:
          key: CODER_ACCESS_URL
          name: coder
  version: 0.22.0
namespace: coder
resources:
- resource-namespace-coder.yaml
- resource-externalsecret-coder.yaml
