#ManagedBy: cue

patches: []
resources:
  - resource-namespace-external-dns.yaml
namespace: external-dns
helmCharts:
  - releaseName: external-dns
    name: external-dns
    version: 1.12.2
    repo: https://kubernetes-sigs.github.io/external-dns
    namespace: external-dns
    valuesInline:
      sources:
        - service
        - ingress
      provider: cloudflare
      domainFilters:
        - defn.run
    includeCRDs: true
