apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: vcluster-control-vc3-cert-manager
  namespace: argocd
spec:
  destination:
    name: vcluster-control-vc3
  project: default
  source:
    path: r/cert-manager
    repoURL: https://github.com/defn/m
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
