#ManagedBy: cue

patches: []
resources:
  - resource-namespace-coder.yaml
namespace: coder
helmCharts:
  - releaseName: coder
    name: coder
    version: 0.22.0
    repo: https://helm.coder.com/v2
    namespace: coder
    valuesInline: {}
    includeCRDs: true
