#ManagedBy: cue

patches: []
resources:
  - resource-namespace-kyverno.yaml
  - resource-clusterrole-create-clusterissuers.yaml
namespace: kyverno
helmCharts:
  - releaseName: kyverno
    name: kyverno
    version: 2.7.2
    repo: https://kyverno.github.io/kyverno
    namespace: kyverno
    valuesInline:
      replicaCount: 1
    includeCRDs: true
