helmCharts:
- includeCRDs: true
  name: traefik
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesInline:
    logs:
      access:
        enabled: true
      general:
        level: DEBUG
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
  version: 22.1.0
namespace: traefik
patches:
- path: patch-service-tailscale.yaml
resources:
- resource-namespace-traefik.yaml
- resource-tlsstore-traefik.yaml
- resource-middleware-http-to-https.yaml
