helmCharts:
- includeCRDs: true
  name: vcluster
  namespace: global-vc0
  releaseName: vcluster
  repo: https://charts.loft.sh
  valuesInline:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - global
    fallbackHostDns: true
    multiNamespaceMode:
      enabled: true
    service:
      loadBalancerClass: tailscale
      type: LoadBalancer
    sync:
      generic:
        clusterRole:
          extraRules:
          - apiGroups:
            - apiextensions.k8s.io
            resources:
            - customresourcedefinitions
            verbs:
            - get
            - list
            - watch
        config: "version: v1beta1\nexport:\n  - apiVersion: serving.knative.dev/v1\n\tkind:
          Service\n\tpatches:\n\t  - op: copyFromObject\n\t\tfromPath: .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath:
          .metadata.annnotations['argocd.argoproj.io/tracking-id']\n  - apiVersion:
          serving.knative.dev/v1\n\tkind: Configuration\n\tpatches:\n\t  - op: copyFromObject\n\t\tfromPath:
          .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath: .metadata.annnotations['argocd.argoproj.io/tracking-id']\n
          \ - apiVersion: serving.knative.dev/v1\n\tkind: Revision\n\tpatches:\n\t
          \ - op: copyFromObject\n\t\tfromPath: .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath:
          .metadata.annnotations['argocd.argoproj.io/tracking-id']\n  - apiVersion:
          serving.knative.dev/v1\n\tkind: Route\n\tpatches:\n\t  - op: copyFromObject\n\t\tfromPath:
          .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath: .metadata.annnotations['argocd.argoproj.io/tracking-id']\nimport:\n
          \ - apiVersion: serving.knative.dev/v1\n\tkind: Service\n\tpatches:\n\t
          \ - op: copyFromObject\n\t\tfromPath: .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath:
          .metadata.annnotations['argocd.argoproj.io/tracking-id']\n  - apiVersion:
          serving.knative.dev/v1\n\tkind: Configuration\n\tpatches:\n\t  - op: copyFromObject\n\t\tfromPath:
          .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath: .metadata.annnotations['argocd.argoproj.io/tracking-id']\n
          \ - apiVersion: serving.knative.dev/v1\n\tkind: Revision\n\tpatches:\n\t
          \ - op: copyFromObject\n\t\tfromPath: .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath:
          .metadata.annnotations['argocd.argoproj.io/tracking-id']\n  - apiVersion:
          serving.knative.dev/v1\n\tkind: Route\n\tpatches:\n\t  - op: copyFromObject\n\t\tfromPath:
          .metadata.annotations['argocd.argoproj.io/tracking-id']\n\t\tpath: .metadata.annnotations['argocd.argoproj.io/tracking-id']"
        role:
          extraRules:
          - apiGroups:
            - serving.knative.dev
            resources:
            - services
            - configurations
            - revisions
            - routes
            verbs:
            - create
            - delete
            - patch
            - update
            - get
            - list
            - watch
      nodes:
        enabled: true
        nodeSelector: env=global
    syncer:
      extraArgs:
      - --tls-san=vcluster.global-vc0.svc.cluster.local
      - --enforce-toleration=env=global-vc0:NoSchedule
    tolerations:
    - key: env
      operator: Equal
      value: global
    vcluster:
      image: rancher/k3s:v1.24.13-k3s1
  version: 0.15.0
namespace: global-vc0
resources:
- resource-namespace-vcluster.yaml
