#ManagedBy: cue

patches: []
namespace: global-vc0
resources:
  - resource-namespace-vcluster.yaml
helmCharts:
  - releaseName: vcluster
    namespace: global-vc0
    valuesInline:
      vcluster:
        image: rancher/k3s:v1.24.13-k3s1
      syncer:
        extraArgs:
          - --tls-san=vcluster.global-vc0.svc.cluster.local
          - --enforce-toleration=env=global-vc0:NoSchedule
      sync:
        nodes:
          enabled: true
          nodeSelector: env=global
        generic:
          clusterRole:
            extraRules:
              - apiGroups:
                  - apiextensions.k8s.io
                resources:
                  - customresourcedefinitions
                verbs:
                  - get
                  - list
                  - watch
          role:
            extraRules:
              - apiGroups:
                  - dapr.io
                resources:
                  - components
                  - configurations
                  - resiliencies
                  - subscriptions
                verbs:
                  - create
                  - delete
                  - patch
                  - update
                  - get
                  - list
                  - watch
          config: |-
            version: v1beta1
            export:
              - kind: Component
                apiVersion: dapr.io/v1alpha1
              - kind: Configuration
                apiVersion: dapr.io/v1alpha1
              - kind: Resiliency
                apiVersion: dapr.io/v1alpha1
              - kind: Subscription
                apiVersion: dapr.io/v1alpha1
      tolerations:
        - key: env
          value: global
          operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - global
      fallbackHostDns: true
      multiNamespaceMode:
        enabled: true
      service:
        type: LoadBalancer
        loadBalancerClass: tailscale
    name: vcluster
    version: 0.15.0
    repo: https://charts.loft.sh
    includeCRDs: true
