apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bye
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bye.defn.run
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: bye
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: bye.defn.run
    http:
      paths:
      - backend:
          service:
            name: bye
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hello.defn.run
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: hello
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: hello.defn.run
    http:
      paths:
      - backend:
          service:
            name: hello
            port:
              number: 80
        path: /
        pathType: Prefix
