#ManagedBy: cue

patches: []
resources: []
helmCharts:
  - releaseName: bootstrap
    valuesInline:
      anyResources:
        nginx: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: vcluster-global-vc0-nginx
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: vcluster-global-vc0
            source:
              repoURL: https://github.com/defn/m
              targetRevision: main
              path: r/nginx
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        hello: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: vcluster-global-vc0-hello
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: vcluster-global-vc0
            source:
              repoURL: https://github.com/defn/m
              targetRevision: main
              path: r/hello
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    includeCRDs: true
