#ManagedBy: cue

patches: []
resources:
  - resource-namespace-argo-workflows.yaml
namespace: argo-workflows
helmCharts:
  - releaseName: argo-workflows
    name: argo-workflows
    version: 0.23.0
    repo: https://argoproj.github.io/argo-helm
    namespace: argo-workflows
    valuesInline:
      controller:
        workflowNamespaces:
          - argo-workflows
    includeCRDs: true
