repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^build/
      - id: end-of-file-fixer
        exclude: ^build/
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: check-toml
      - id: check-shebang-scripts-are-executable
